logging:
  level:
    com:
      mycompany:
        myapp: INFO
spring:
  application:
    name: JhipsterSampleApplication
  jackson:
    default-property-inclusion: non_absent
  security:
    user:
      name: admin
      password: $2a$12$cRKS9ZURbdJIaRsKDTDUmOrH4.B.2rokv8rrkrQXr2IR2Hkna484O
      roles: ADMIN
server:
  port: 8080
application:
  security:
    jwt-base64-secret: NTczOTI0OTA5YTliY2FjYWQ0OTAwNWQyYTI4ODBjY2ExZmM0MjRhMmI0ODIxMGU1OWU4ODg3ZTg0ZTljNjcyYw==
    content-security-policy: "default-src 'self'; frame-src 'self' data:; script-src
      'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com; style-src
      'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data:;
      font-src 'self' data: https://fonts.gstatic.com;"
    remember-me-token-validity: P365D
    token-validity: P1D
springdoc:
  enable-native-support: true
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    tryItOutEnabled: true
